version: '3'
services:
  Dock2Date:
    container_name: Dock2Date
    hostname: Dock2Date
    image: ghcr.io/daMustermann/Dock2Date
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=America/New_York
      - LANGUAGE=en
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/pydock2date/hooks:/app/pydock2date/hooks
    ports:
      - "9999:9999"  # Web UI port (if WEB=true)
